# Generated by Django 2.2.4 on 2020-05-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
    ]
