# Generated by Django 2.2.4 on 2020-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='comment', max_length=255),
            preserve_default=False,
        ),
    ]
